apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Diamond-Carat-Calculator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chankyswami/Diamond-Carat-Calculator-deployment.git'
    targetRevision: main
    path: .
  destination:
    server: https://172.16.16.100:6443
    namespace: Diamond-Carat-Calculator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true