apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamond-carat-calculator
  namespace: diamond-carat-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diamond-carat-calculator
  template:
    metadata:
      labels:
        app: diamond-carat-calculator
    spec:
      containers:
        - name: diamond-carat-calculator
          image: docker.io/chankyswami/diamond-carat-calculator:2cdf00c
          ports:
            - containerPort: 5000