---
apiVersion: v1
kind: Service
metadata:
  name: diamond-carat-calculator
  namespace: diamond-carat-calculator
spec:
  selector:
    app: diamond-carat-calculator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30090
  type: NodePort